# Generated by Django 4.0 on 2023-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='demomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('DOB', models.DateField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Demomodels',
        ),
    ]
